name: ProjectEuler
version: 0.1.0.0
github: "Javran/ProjectEuler"
license: MIT
author: "Javran Cheng"
maintainer: "Javran.C@gmail.com"
copyright: "Copyright: (c) 2019 Javran Cheng"
description: "Javran's ProjectEuler Workspace"

extra-source-files:
- README.md

data-files:
- data/*.txt
- data/*.yaml

dependencies:
- aeson
- arithmoi
- array
- base
- containers
- data-ordlist
- dlist
- filepath
- foldl
- lens
- lifted-base
- microstache
- monad-control
- MonadRandom
- mtl
- parsec
- petbox
- PSQueue
- split
- strict
- system-filepath
- bytestring
- text
- text-show
- time
- transformers-base
- turtle
- unordered-containers
- vector
- file-embed
- scientific
- utility-ht
- yaml
- deepseq

_exec-ghc-options: &exe-ghc-options
  - -threaded
  - -O2
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src

  exposed-modules:
    - ProjectEuler.Types
    - ProjectEuler.GetData
    - ProjectEuler.AllProblems
    - ProjectEuler.Main
    # The following section should be modified automatically by "templater"
    # ==== PROBLEM_MODULE_LIST_BEGIN
    - ProjectEuler.Problem1
    - ProjectEuler.Problem2
    - ProjectEuler.Problem3
    - ProjectEuler.Problem4
    - ProjectEuler.Problem5
    - ProjectEuler.Problem6
    - ProjectEuler.Problem7
    - ProjectEuler.Problem8
    - ProjectEuler.Problem9
    - ProjectEuler.Problem10
    - ProjectEuler.Problem11
    - ProjectEuler.Problem12
    - ProjectEuler.Problem13
    - ProjectEuler.Problem14
    - ProjectEuler.Problem15
    - ProjectEuler.Problem16
    - ProjectEuler.Problem17
    - ProjectEuler.Problem18
    - ProjectEuler.Problem19
    - ProjectEuler.Problem20
    - ProjectEuler.Problem21
    - ProjectEuler.Problem22
    - ProjectEuler.Problem23
    - ProjectEuler.Problem24
    - ProjectEuler.Problem25
    - ProjectEuler.Problem26
    - ProjectEuler.Problem27
    - ProjectEuler.Problem28
    - ProjectEuler.Problem29
    - ProjectEuler.Problem30
    - ProjectEuler.Problem31
    - ProjectEuler.Problem32
    - ProjectEuler.Problem33
    - ProjectEuler.Problem34
    - ProjectEuler.Problem35
    - ProjectEuler.Problem36
    - ProjectEuler.Problem37
    - ProjectEuler.Problem38
    - ProjectEuler.Problem39
    - ProjectEuler.Problem40
    - ProjectEuler.Problem41
    - ProjectEuler.Problem42
    - ProjectEuler.Problem43
    - ProjectEuler.Problem44
    - ProjectEuler.Problem45
    - ProjectEuler.Problem46
    - ProjectEuler.Problem47
    - ProjectEuler.Problem48
    - ProjectEuler.Problem49
    - ProjectEuler.Problem50
    - ProjectEuler.Problem51
    - ProjectEuler.Problem52
    - ProjectEuler.Problem53
    - ProjectEuler.Problem54
    - ProjectEuler.Problem55
    - ProjectEuler.Problem56
    - ProjectEuler.Problem57
    - ProjectEuler.Problem58
    - ProjectEuler.Problem59
    - ProjectEuler.Problem60
    - ProjectEuler.Problem61
    - ProjectEuler.Problem62
    - ProjectEuler.Problem63
    - ProjectEuler.Problem64
    - ProjectEuler.Problem65
    - ProjectEuler.Problem67
    - ProjectEuler.Problem68
    - ProjectEuler.Problem69
    - ProjectEuler.Problem70
    - ProjectEuler.Problem71
    - ProjectEuler.Problem72
    - ProjectEuler.Problem73
    - ProjectEuler.Problem74
    - ProjectEuler.Problem75
    - ProjectEuler.Problem76
    - ProjectEuler.Problem77
    - ProjectEuler.Problem78
    - ProjectEuler.Problem79
    - ProjectEuler.Problem84
    - ProjectEuler.Problem87
    - ProjectEuler.Problem88
    - ProjectEuler.Problem92
    - ProjectEuler.Problem97
    - ProjectEuler.Problem104
    - ProjectEuler.Problem206
    # ==== PROBLEM_MODULE_LIST_END

executables:
  pet:
    main: Main.hs
    source-dirs: src

    dependencies:
      - ProjectEuler

    ghc-options: *exe-ghc-options

  templater:
    main: Main.hs
    source-dirs: templater

    other-modules:
    - Common
    - CmdSync
    - CmdMigrate
    - CmdCreate
    - CmdStat

    ghc-options: *exe-ghc-options

tests:
  hspec:
    main: Spec.hs

    source-dirs:
      - test
      - src
    dependencies:
      - hspec
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
