name:                ProjectEuler
version:             0.1.0.0
github:              "Javran/ProjectEuler"
license:             MIT
author:              "Javran Cheng"
maintainer:          "Javran.C@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         "Javran's ProjectEuler Workspace"

extra-source-files:
- README.md

data-files:
- data/*.txt

dependencies:
- base

executables:
  pet:
    main:                Main.hs
    source-dirs:         src

    dependencies:
    - petbox
    - primes
    - data-ordlist
    - strict
    - array
    - containers
    - split
    - filepath
    - mtl
    - parsec
    - PSQueue
    - lens
    - MonadRandom
    - arithmoi
    - text
    - text-show
    - dlist
    - lifted-base
    - monad-control
    - transformers-base

    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N

    other-modules: 
    - Paths_ProjectEuler
    - ProjectEuler.Types
    - ProjectEuler.GetData
    - ProjectEuler.AllProblems
    # The following section should be modified automatically by "templater"
    # ==== PROBLEM_MODULE_LIST_BEGIN
    - ProjectEuler.Problem1
    - ProjectEuler.Problem2
    - ProjectEuler.Problem3
    - ProjectEuler.Problem4
    - ProjectEuler.Problem5
    - ProjectEuler.Problem6
    - ProjectEuler.Problem7
    - ProjectEuler.Problem24
    # ==== PROBLEM_MODULE_LIST_END

  templater:
    main: Main.hs
    source-dirs: templater

    dependencies:
    - microstache
    - turtle
    - system-filepath
    - aeson
    - text
    - text-show
    - unordered-containers
    - foldl
    - vector
    - containers
    - time
    - strict

    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N

    other-modules:
    - Common
    - CmdSync
    - CmdMigrate
    - CmdCreate
    - CmdStat
