name:                ProjectEuler
version:             0.1.0.0
github:              "Javran/ProjectEuler"
license:             MIT
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         "Javran's ProjectEuler Workspace"

extra-source-files:
- README.md

data-files:
- data/*.txt

dependencies:
- base
- petbox

executables:
  pet:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
