name:                ProjectEuler
version:             0.1.0.0
github:              "Javran/ProjectEuler"
license:             MIT
author:              "Javran Cheng"
maintainer:          "Javran.C@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         "Javran's ProjectEuler Workspace"

extra-source-files:
- README.md

data-files:
- data/*.txt

dependencies:
- base

executables:
  pet:
    main:                Main.hs
    source-dirs:         src

    dependencies:
    - petbox
    - primes
    - data-ordlist
    - strict
    - array
    - containers
    - split
    - filepath
    - mtl
    - parsec
    - PSQueue
    - lens
    - MonadRandom

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    other-modules: 
    - Paths_ProjectEuler
    - ProjectEuler.Types
    - ProjectEuler.GetData
    - ProjectEuler.AllProblems
    - ProjectEuler.Problem1
    - ProjectEuler.Problem24

  templater:
    main: Main.hs
    source-dirs: templater

    dependencies:
    - microstache
    - turtle
    - system-filepath
    - aeson
    - text
    - unordered-containers

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
