name: ProjectEuler
version: 0.1.0.0
github: "Javran/ProjectEuler"
license: MIT
author: "Javran Cheng"
maintainer: "Javran.C@gmail.com"
copyright: "Copyright: (c) 2019 Javran Cheng"
description: "Javran's ProjectEuler Workspace"

extra-source-files:
- README.md

data-files:
- data/*.txt
- data/*.yaml

dependencies:
- aeson
- arithmoi
- array
- base
- containers
- data-ordlist
- dlist
- filepath
- foldl
- lens
- lifted-base
- microstache
- monad-control
- MonadRandom
- mtl
- parsec
- petbox
- PSQueue
- split
- strict
- system-filepath
- bytestring
- text
- text-show
- time
- transformers-base
- turtle
- unordered-containers
- vector
- file-embed
- scientific
- utility-ht
- yaml
- deepseq

_exec-ghc-options: &exe-ghc-options
  - -threaded
  - -O2
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src

  exposed-modules:
    - ProjectEuler.Types
    - ProjectEuler.GetData
    - ProjectEuler.AllProblems
    - ProjectEuler.Main
    # The following section should be modified automatically by "templater"
    # ==== PROBLEM_MODULE_LIST_BEGIN
    - ProjectEuler.Problem1
    - ProjectEuler.Problem2
    - ProjectEuler.Problem3
    - ProjectEuler.Problem4
    - ProjectEuler.Problem5
    - ProjectEuler.Problem6
    - ProjectEuler.Problem7
    - ProjectEuler.Problem8
    - ProjectEuler.Problem9
    - ProjectEuler.Problem10
    - ProjectEuler.Problem11
    - ProjectEuler.Problem12
    - ProjectEuler.Problem13
    - ProjectEuler.Problem14
    - ProjectEuler.Problem15
    - ProjectEuler.Problem16
    - ProjectEuler.Problem17
    - ProjectEuler.Problem18
    - ProjectEuler.Problem19
    - ProjectEuler.Problem20
    - ProjectEuler.Problem21
    - ProjectEuler.Problem22
    - ProjectEuler.Problem23
    - ProjectEuler.Problem24
    - ProjectEuler.Problem26
    - ProjectEuler.Problem27
    - ProjectEuler.Problem35
    - ProjectEuler.Problem36
    - ProjectEuler.Problem38
    - ProjectEuler.Problem43
    - ProjectEuler.Problem44
    - ProjectEuler.Problem47
    - ProjectEuler.Problem60
    - ProjectEuler.Problem70
    - ProjectEuler.Problem206
    # ==== PROBLEM_MODULE_LIST_END

executables:
  pet:
    main: Main.hs
    source-dirs: src

    dependencies:
      - ProjectEuler

    ghc-options: *exe-ghc-options

  templater:
    main: Main.hs
    source-dirs: templater

    other-modules:
    - Common
    - CmdSync
    - CmdMigrate
    - CmdCreate
    - CmdStat

    ghc-options: *exe-ghc-options

tests:
  hspec:
    main: Spec.hs

    source-dirs:
      - test
      - src
    dependencies:
      - hspec
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
